[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; N8R2 = 8MB Flash (QIO) + 2MB PSRAM (QSPI)
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_upload.flash_size = 8MB

build_flags =
    -DBOARD_HAS_PSRAM

lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library